## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [6]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df

,City_ID,City_ID.1,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
0,0,0,Atuona,PF,-9.8000,-139.0333,80.13,74,85,15.46,overcast clouds,Villa Enata
1,18,18,Pyay,MM,18.8167,95.2167,84.11,64,53,5.61,broken clouds,Shwe Pyi Thar
2,24,24,Kununurra,AU,-15.7667,128.7333,87.80,33,100,14.97,overcast clouds,Hotel Kununurra
3,35,35,Salalah,OM,17.0151,54.0924,80.60,74,40,3.44,scattered clouds,HAMDAN PLAZA HOTEL SALALAH
4,36,36,Hithadhoo,MV,-0.6000,73.0833,82.42,68,39,4.38,scattered clouds,Scoop Guest House
...,...,...,...,...,...,...,...,...,...,...,...,...
92,662,662,Balikpapan,ID,-1.2675,116.8289,80.96,78,65,3.91,broken clouds,ibis Balikpapan
93,663,663,Kanbe,MM,16.7053,96.0017,82.40,83,40,3.44,scattered clouds,CBT Mingalar Bar Bio Garden
94,666,666,Contramaestre,CU,20.2978,-76.2414,80.60,78,75,9.22,broken clouds,Hotel Caribeño
95,671,671,Banda Aceh,ID,5.5577,95.3222,81.07,73,97,5.41,overcast clouds,Sulthan Hotel International
96,672,672,Biak,ID,-0.9131,122.8766,81.61,67,98,5.55,overcast clouds,Penginapan Kim

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df['City'] == 'Pochutla']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Acapulco']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Celestun']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'San Andres'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Boa Vista']

In [8]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start['Lat'].to_numpy()[0], vacation_start['Lng'].to_numpy()[0])
end = (vacation_end['Lat'].to_numpy()[0], vacation_end['Lng'].to_numpy()[0])
stop1 = (vacation_stop1['Lat'].to_numpy()[0], vacation_stop1['Lng'].to_numpy()[0])
stop2 = (vacation_stop2['Lat'].to_numpy()[0], vacation_stop2['Lng'].to_numpy()[0])
stop3 = (vacation_stop3['Lat'].to_numpy()[0], vacation_stop3['Lng'].to_numpy()[0])

In [9]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
vacation_driving_trip = gmaps.directions_layer(start, end, waypoints=[stop1, stop2, stop3], travel_mode='DRIVING')
fig.add_layer(vacation_driving_trip)
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3, vacation_end],ignore_index=True)
itinerary_df

,City_ID,City_ID.1,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Hotel Name
0,101,101,Pochutla,MX,15.7432,-96.4661,84.2,65,90,9.22,overcast clouds,Hotel Posada San Jose
1,344,344,Celestun,MX,20.8667,-90.4000,80.1,75,3,13.02,clear sky,Posada Lilia
2,135,135,San Andres,CO,12.5847,-81.7006,82.4,78,40,9.22,scattered clouds,Hotel Arena Blanca
3,516,516,Boa Vista,BR,2.8197,-60.6733,80.6,83,75,2.30,broken clouds,Aipana Plaza Hotel
4,106,106,Acapulco,MX,16.8634,-99.8901,82.4,78,90,5.75,overcast clouds,HS Hotsson Smart Acapulco

In [11]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""


# 10a Get the data from each row and add it to the formatting template and store the data in a list.
it_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
marker_layer = gmaps.marker_layer(locations, info_box_content=it_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))